import { 
    FaDiceD20,
    FaSimCard,
    FaAtom,
    FaDiceTwo,
    FaUsers,
    FaFistRaised,
    FaMotorcycle,
    FaDungeon,
    FaCoins,
    FaBomb, 
    FaChessKing, 
    FaShieldAlt, 
    FaMagic, 
    FaPuzzlePiece, 
    FaCrosshairs, 
    FaGlasses,
    FaBong,
    FaFootballBall } from 'react-icons/fa';



export const genres = [
    {
        "id": 4,
        "name": "Action",
        "slug": "action",
        "icon": <FaBomb />,
        "games_count": 172072,
    },
    {
        "id": 51,
        "name": "Indie",
        "slug": "indie",
        "icon": <FaGlasses />,
        "games_count": 49894,
    },
    {
        "id": 3,
        "name": "Adventure",
        "slug": "adventure",
        "icon": <FaMagic/>,
        "games_count": 131854,
    },
    {
        "id": 5,
        "name": "RPG",
        "slug": "role-playing-games-rpg",
        'icon': <FaShieldAlt/>,
        "games_count": 52210,
    },
    {
        "id": 10,
        "name": "Strategy",
        "slug": "strategy",
        "icon": <FaChessKing/>,
        "games_count": 51972,
    },
    {
        "id": 2,
        "name": "Shooter",
        "slug": "shooter",
        'icon': <FaCrosshairs/>,
        "games_count": 60706,
    },
    {
        "id": 40,
        "name": "Casual",
        "slug": "casual",
        "icon": <FaBong/>,
        "games_count": 42444,
    },
    {
        "id": 7,
        "name": "Puzzle",
        "slug": "puzzle",
        "icon": <FaPuzzlePiece/>,
        "games_count": 97045,
    },
    {
        "id": 11,
        "name": "Arcade",
        "slug": "arcade",
        "icon": <FaCoins/>,
        "games_count": 22530,
    },
    {
        "id": 83,
        "name": "Platformer",
        "slug": "platformer",
        "icon": <FaDiceD20/>,
        "games_count": 101950,
    },
    {
        "id": 1,
        "name": "Racing",
        "slug": "racing",
        "icon": <FaMotorcycle/>,
        "games_count": 23947,
    },
    {
        "id": 59,
        "name": "Massively Multiplayer",
        "slug": "massively-multiplayer",
        "icon": <FaDungeon/>,
        "games_count": 3111,
    },
    {
        "id": 15,
        "name": "Sports",
        "slug": "sports",
        "icon": <FaFootballBall/>,
        "games_count": 20399,
    },
    {
        "id": 6,
        "name": "Fighting",
        "slug": "fighting",
        "icon": <FaFistRaised/>,
        "games_count": 11860,
    },
    {
        "id": 19,
        "name": "Family",
        "slug": "family",
        "icon": <FaUsers/>,
        "games_count": 5378,
    },
    {
        "id": 28,
        "name": "Board Games",
        "slug": "board-games",
        "icon": <FaDiceTwo/>,
        "games_count": 8240,
      },
    {
        "id": 34,
        "name": "Educational",
        "slug": "educational",
        "icon": <FaAtom/>,
        "games_count": 15592,
    },
    {
        "id": 17,
        "name": "Card",
        "slug": "card",
        "icon": <FaSimCard/>,
        "games_count": 4435,
       }
]